DROP TABLE IF EXISTS partner;

CREATE TABLE partners (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  companyName VARCHAR(255) NOT NULL,
  ref VARCHAR(255) NOT NULL,
  locale VARCHAR(5) DEFAULT NULL,
  expires DATETIME
);